# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from functions_combinaisons import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.dices = []
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        pushButton_1.setGeometry(QtCore.QRect(70, 40, 100, 100))
        pushButton_1.setStyleSheet(
            "border-image : url(images/dice1.png);")
        pushButton_1.setText("")
        pushButton_1.setCheckable(True)
        pushButton_1.setObjectName("pushButton")
        pushButton_1.clicked.connect(self.btnstate)
        self.dices.append(pushButton_1)

        pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        pushButton_2.setGeometry(QtCore.QRect(210, 40, 100, 100))
        pushButton_2.setStyleSheet(
            "border-image : url(images/dice2.png);")
        pushButton_2.setText("")
        pushButton_2.setCheckable(True)
        pushButton_2.setObjectName("pushButton_2")
        pushButton_2.clicked.connect(self.btnstate)
        self.dices.append(pushButton_2)

        pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        pushButton_3.setGeometry(QtCore.QRect(350, 40, 100, 100))
        pushButton_3.setStyleSheet(
            "border-image : url(images/dice3.png);")
        pushButton_3.setText("")
        pushButton_3.setCheckable(True)
        pushButton_3.setObjectName("pushButton_3")
        pushButton_3.clicked.connect(self.btnstate)
        self.dices.append(pushButton_3)

        pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        pushButton_4.setGeometry(QtCore.QRect(490, 40, 100, 100))
        pushButton_4.setStyleSheet(
            "border-image : url(images/dice4.png);")
        pushButton_4.setText("")
        pushButton_4.setCheckable(True)
        pushButton_4.setObjectName("pushButton_4")
        pushButton_4.clicked.connect(self.btnstate)
        self.dices.append(pushButton_4)

        pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        pushButton_5.setGeometry(QtCore.QRect(630, 40, 100, 100))
        pushButton_5.setStyleSheet(
            "border-image : url(images/dice5.png);")
        pushButton_5.setText("")
        pushButton_5.setCheckable(True)
        pushButton_5.setObjectName("pushButton_5")
        pushButton_5.clicked.connect(self.btnstate)
        self.dices.append(pushButton_5)

        # bt lancer
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(70, 190, 280, 60))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setText("Lancer")
        self.pushButton_6.clicked.connect(self.btnRoll)

        # bt marquer
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(450, 190, 280, 60))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setText("Marquer")

        


        MainWindow.setCentralWidget(self.centralwidget)

        # self.tableView = QtWidgets.QTableView(self.centralwidget)
        # self.tableView.setGeometry(QtCore.QRect(50, 290, 256, 192))
        # self.tableView.setObjectName("tableView")
        # self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        # self.tableView_2.setGeometry(QtCore.QRect(370, 290, 256, 192))
        # self.tableView_2.setObjectName("tableView_2")
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        # self.retranslateUi(MainWindow)
        # QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # def retranslateUi(self, MainWindow):
    #     _translate = QtCore.QCoreApplication.translate
    #     MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
    #     pushButton_6.setText(_translate("MainWindow", "Lancer"))
    #     pushButton_7.setText(_translate("MainWindow", "Marquer"))

    def btnstate(self):
        if pushButton_1.isChecked():
            pushButton_1.setStyleSheet("border-image : url(images/dice1_red.png);")
        else:
            pushButton_1.setStyleSheet("border-image : url(images/dice1.png);")

        if pushButton_2.isChecked():
            pushButton_2.setStyleSheet("border-image : url(images/dice2_red.png);")
        else:
            pushButton_2.setStyleSheet("border-image : url(images/dice2.png);")

        if pushButton_3.isChecked():
            pushButton_3.setStyleSheet("border-image : url(images/dice3_red.png);")
        else:
            pushButton_3.setStyleSheet("border-image : url(images/dice3.png);")

        if pushButton_4.isChecked():
            pushButton_4.setStyleSheet("border-image : url(images/dice4_red.png);")
        else:
            pushButton_4.setStyleSheet("border-image : url(images/dice4.png);")

        if pushButton_5.isChecked():
            pushButton_5.setStyleSheet("border-image : url(images/dice5_red.png);")
        else:
            pushButton_5.setStyleSheet("border-image : url(images/dice5.png);")

    # lancer des dés
    def btnRoll(self):
        # dice_url = ["images/dice1.png",
        #             "images/dice2.png",
        #             "images/dice3.png",
        #             "images/dice4.png",
        #             "images/dice5.png",
        #             "images/dice6.png",
        #             ]

        print("lancer:", roll_dice(5))
        # for i in range (1,6):
            # print("dice", self."pushButton_"+str(i))
            # pushButton_+str(i).setStyleSheet("border-image: url(image/dice" + (i-1) + ".png)")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
